name: check

on: push

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@v7.0
        with:
          version: 30.1
      - uses: leotaku/elisp-check@v1.4.1
        with:
          warnings_as_errors: true
